# Generated by Django 4.2 on 2023-04-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_master', models.CharField(max_length=100)),
                ('rang_master', models.IntegerField()),
                ('phone_master', models.IntegerField()),
                ('statys_master', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100)),
                ('time_service', models.IntegerField()),
                ('price_service', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('start_work', models.TimeField()),
                ('end_work', models.TimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.master')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='services_master',
            field=models.ManyToManyField(to='Salon.services'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('start_time', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.master')),
                ('services_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.services')),
            ],
        ),
    ]
