# Generated by Django 4.2 on 2023-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(),
        ),
    ]
