# Generated by Django 4.2 on 2023-04-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0003_alter_schedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='rang_master',
            new_name='rank_master',
        ),
    ]
