# Generated by Django 4.2 on 2023-04-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0004_rename_rang_master_master_rank_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='client_id',
            new_name='client_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
